### ISSUE TITLE
Player controllers not showing

### ISSUE THREAD

**Issue by YasiruDev** [ooyala/html5-skin#1189]
video controllers are not showing in my player.below is my configurations

var playerParam = {
            "pcode": "my_pcode",
            "playerBrandingId": "my_branding",
            "debug": false,
            "skin": {
                "config": "http://player.ooyala.com/static/v4/production/latest/skin-plugin/skin.json",
                "inline": {
                    "startScreen": { "showDescription": false, "playIconStyle": { "color": "blue" } }
                },
                "skipControls": {
                    "enabled": true,
                    "skipBackwardTime": 5,
                    "skipForwardTime": 30
                }
            }
        };

**Comment by zelibobla** [comment]
@YasiruDev provide a bit more info, please. Is this related to a server side rendering as your previous question? What do you mean under 'showing'? What exact state of the app do you expect?

**Comment by veer3383** [comment]
I am also facing the same issue when using` /v4/production/latest/`

for skin.json i am  using `/v4/stable/4.31.17/ ` and by removing html5-skin from my project solves my issue of control bar. (i.e. now i can see control bar like the way it was before. Also, i can now toggle the video full screen on chrome. Thats the reason why i updated the player )

If i include html5-skin > `/v4/stable/4.20.8/ ` It throws some weird react error in the console like this.

error : 
```
react-dom.production.min.js:13 Uncaught Invariant Violation: Minified React error #188; visit https://reactjs.org/docs/error-decoder.html?invariant=188 for the full message or use the non-minified dev environment for full errors and additional helpful warnings. 
    at http://player.ooyala.com/static/v4/stable/4.31.17/skin-plugin/html5-skin.min.js:1:524946
    at V (http://player.ooyala.com/static/v4/stable/4.31.17/skin-plugin/html5-skin.min.js:1:525049)
    at http://player.ooyala.com/static/v4/stable/4.31.17/skin-plugin/html5-skin.min.js:1:548897
    at on (http://player.ooyala.com/static/v4/stable/4.31.17/skin-plugin/html5-skin.min.js:1:548934)
    at Object.findDOMNode (http://player.ooyala.com/static/v4/stable/4.31.17/skin-plugin/html5-skin.min.js:1:614892)
    at r.generateResponsiveData (http://player.ooyala.com/static/v4/stable/4.31.17/skin-plugin/html5-skin.min.js:1:325337)
    at r.onResize (http://player.ooyala.com/static/v4/stable/4.31.17/skin-plugin/html5-skin.min.js:1:325157)
    at n (http://player.ooyala.com/static/v4/stable/4.31.17/skin-plugin/html5-skin.min.js:1:513587)
    at g (http://player.ooyala.com/static/v4/stable/4.31.17/skin-plugin/html5-skin.min.js:1:513657)
```
